### ISSUE TITLE
Pullup resistors are needed

### ISSUE THREAD

**Issue by jake-g00dwin** [Personal-Data-Acquisition/pda_hardware#10]
It seems like we may be using more sensors in i2c than previously thought.

It may be a good idea for us to acquire some pull-up resistors for testing if nothing else. Given short lines 4.7k is fine, but ideally we'll adjust R values for the bus capacitance in the PCB design.

- [ ] Get some pull-up resistors for prototype builds
- [ ] size R values according to i2c speed and bus length(capacitance).

**Comment by jake-g00dwin** [comment]
I'm using 10k resistors in parallel right now and I think I might have some 4.7k ones somewhere but it might be a bit cleaner on our prototypes to not increase the component count like that.

**Comment by crispyDyne** [comment]
Do you need me to order something? What product specifically do you need?

**Comment by jake-g00dwin** [comment]
For any of the modules we decide to use i2c on we will need some 4.7k resistors(2 per i2c bus). It's a conservative value for the SDA/SCL lines assuming we don't need to run the sensor's themselves off board/pcb away from the micro-controllers.

This is more so something that could cause problems once we have the semi-finished prototype actually logging data if there is any ambient EMI or we decide to use faster i2c modes past the 100KHz standard spec to use the Fastmode(400KHz) or Fastmode+ (1MHz) on sensors.

It will help with the blocking operation of i2c devices with embedded-hal 2.x crate because all the i2c operations/traits for the older embedded-hal are setup for blocking operation.

**Comment by jake-g00dwin** [comment]
closing issue as we have enough parts for testing at the moment.
